# Generated by Django 3.1.7 on 2021-03-25 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210323_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='website_url',
            new_name='linkedin_url',
        ),
    ]
